### ISSUE TITLE
target="_blank"

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/adminer#1]
Hi Gregor. 

superklasse! Danke.

Guck doch mal ob folgende Ergänzung der boot.php sinnvoll wäre:

``` php
if (rex::isBackend() && rex::getUser() && rex::getUser()->isAdmin()) {
  rex_extension::register('OUTPUT_FILTER',function(rex_extension_point $ep){
    $suchmuster = '<a href="index.php?page=adminer"><i class="rex-icon fa-database"></i> Adminer</a>';
    $ersetzen = '<a href="index.php?page=adminer" target="_blank"><i class="rex-icon fa-database"></i> Adminer</a>';
    $ep->setSubject(str_replace($suchmuster, $ersetzen, $ep->getSubject()));
  });
}
```

LG
Oliver

**Comment by gharlan** [comment]
target=_blank leuchtet mir ein, aber warum willst du "Adminer" durch "Ayvfsfdminer" ersetzen?

**Comment by olien** [comment]
Ups. war ein Test um nicht draufklicken zu müssen :-)
Ist korrigiert.

**Comment by gharlan** [comment]
Hoffe meine Lösung ist dir auch recht: https://github.com/FriendsOfREDAXO/adminer/commit/2c4dbcc66187fc60dac82a4bc0ed60715d5bb54f ;)

dennoch danke!
