### ISSUE TITLE
update adminer Auf aktuelles release

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/adminer#12]
https://github.com/vrana/adminer/releases/

vllt noch ein paar tage warten, ggf. gibts ja in kürze ein 4.4.1 o.ä.

**Comment by gharlan** [comment]
Gibt mittlerweile 4.5.0

**Comment by tbaddade** [comment]
Gibt mittlerweile 4.6.2

**Comment by gharlan** [comment]
Die aber nicht so ohne Weiteres läuft. Warte daher auf die nächste Version, ich glaube das Problem wurde auf github bereits gefixt.

**Comment by gharlan** [comment]
Ich glaube, es war dieser Commit: https://github.com/vrana/adminer/commit/acee5c0011504bbeba9bc5937a37f3ef3349c57f

**Comment by AWqxKAWERbXo** [comment]
Inzwischen gibt's auch 4.6.2

**Comment by gharlan** [comment]
Jupp, die hat aber das Problem noch, ich warte auf die 4.6.3.

**Comment by tbaddade** [comment]
Wird vermutlich jetzt eine Kommentarschleife 😃 
https://github.com/FriendsOfREDAXO/adminer/issues/12#issuecomment-372701958
