### ISSUE TITLE
Geeignetes Theme für REDAXO

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/adminer#13]
![screenshot](https://user-images.githubusercontent.com/791247/35196707-297dee10-fed6-11e7-9f35-99a7d46fd65e.png)

https://raw.githubusercontent.com/vrana/adminer/master/designs/pappu687/adminer.css

**Comment by AWqxKAWERbXo** [comment]
Die Diskussion gegen oder für ein eigenes Theme hatten wir doch neulich erst? (Ich wäre durchaus dafür offen)

**Comment by IngoWinter** [comment]
Jau, da wurde vor kurzem ein Issue zu geschlossen. Ich bin unverändert der Meinung, dass das originale Adminer Layout bleiben sollte. Es ist übersichtlich, effizient und kompakt.

**Comment by skerbis** [comment]
Ich finde dieses Theme passt sehr gut zum REDAXO Backend

**Comment by skerbis** [comment]
Aber Duplikat ist nun mal Duplikat, daher close https://github.com/FriendsOfREDAXO/adminer/issues/8
