### ISSUE TITLE
rex_sql_table-Code - ensureIndex führt zu Fehler

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/adminer#15]
```
rex_sql_table::get(rex::getTable('dsgvo_client'))
->ensureColumn(new rex_sql_column('`key`', 'text'))
->ensureIndex(new rex_sql_index('`key`', ['`key`'], rex_sql_index::UNIQUE))
->ensure();
```

Dieser Code führt das Problem vor.

**Comment by gharlan** [comment]
Bitte diese Issues eher im Core-Repo anlegen. Das Adminer-Addon nutzt auch nur [`rex_sql_schema_dumper`](https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/lib/sql/schema_dumper.php) und sorgt nur für die Ausgabe (als Alternative zum `db:dump-schema`-Command vom Core).

Also der Code wird so mit den Backsticks ausgespuckt?

**Comment by gharlan** [comment]
Also eigentlich sollten die Backsticks so nicht ausgespuckt werden, und man muss sie auch nicht setzen, bzw. darf es gar nicht, da `rex_sql_table` das schon intern macht.

**Comment by gharlan** [comment]
Bei mir werden bei `key` keine Backsticks hinzugefügt, und der Code lässt sich so auch ausführen, wie er ausgespuckt wird:

![screenshot 2018-03-20 12 15 09](https://user-images.githubusercontent.com/330436/37651476-877ac9d6-2c38-11e8-8861-7ab952e0127e.png)

**Comment by AWqxKAWERbXo** [comment]
Dann war ich evtl. zu voreilig mit den Backticks. Bei mir führte der automatische Code dann zu einem Fehler in der install.php

**Comment by gharlan** [comment]
Kannst du die Fehlermeldung nochmal nachschauen im Systemlog?
