### ISSUE TITLE
Warning | session_cache_limiter() 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/adminer#19]
php 7.2.5

> Warning | session_cache_limiter() [<a href='https://php.net/manual/function.session-cache-limiter'>function.session-cache-limiter</a>]: Cannot change cache limiter when session is active

**Comment by AWqxKAWERbXo** [comment]
+1

**Comment by IngoWinter** [comment]
ich habe die fehlermeldung durch ein ```@``` vor allen ```session_*()``` aufrufen unterdrückt. wenn das für @gharlan akzeptabel ist, mach ich gerne einen pr

**Comment by staabm** [comment]
sind das stellen im adminer selbst?

**Comment by IngoWinter** [comment]
jau

**Comment by staabm** [comment]
ich hab mal nen upstream bug aufgemacht: https://sourceforge.net/p/adminer/bugs-and-features/625/

**Comment by staabm** [comment]
ein fix als PR in https://github.com/vrana/adminer wäre top

**Comment by gharlan** [comment]
Die Funktion wurde hier in das `if` verschoben: https://github.com/vrana/adminer/commit/756e304c924f90b014b81d23fb292166e02ae7dd

Mit der nächsten Version könnten wir vielleicht einfach die Konstante `SID` setzen.

**Comment by staabm** [comment]
hab nen upstream PR geöffnet (Ungetestet)
https://github.com/vrana/adminer/pull/284

**Comment by IngoWinter** [comment]
läuft :)

**Comment by staabm** [comment]
@IngoWinter hattest du den vorgeschlagenen fix mal getestet?

**Comment by IngoWinter** [comment]
Nee. mein "läuft" bezog sich generell auf die Aktivität in diesem Issue.

**Comment by skerbis** [comment]
@gharlan Danke
https://github.com/FriendsOfREDAXO/adminer/pull/20
