### ISSUE TITLE
Doku wie man den adminer updated

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/adminer#22]
Reicht Nur hier im repos, damit es auch andere machen können

**Comment by Koala** [comment]
> Adminer updaten:
> 
> Gehe zu https://github.com/vrana/adminer/releases und suche dort die aktuelle Datei (z.B. adminer-4.7.0.php).
> Kopiere diese nach **redaxo/src/addons/adminer/vendor/**
> Bennene die neue Datei um in **adminer.php**. Zuvor muss die bestehende Datei umbenannt oder gelöscht werden.
> 
> Fertig.
> 

So?

**Comment by staabm** [comment]
es gibt viele unterschiedliche adminer versionen und man muss die "richtige" nehmen

**Comment by gharlan** [comment]
Passt fast so, bloß dass wir die `adminer-4.7.0-mysql.php` nehmen.

**Comment by Koala** [comment]
Ah, habs wie oben von mir beschrieben gemacht. Funktioniert auf den ersten Klick. Hab aber keinen weiteren Test unternommen.
Redaxo  unterstützt nur MySQL? _`(ich bin nicht mehr auf dem Laufenden <duckundweg> (-; )`_

**Comment by staabm** [comment]
mysql und mariadb

**Comment by staabm** [comment]
Danke @Koala
