### ISSUE TITLE
Installer Mindestversion Core anheben

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/adminer#28]
Das Adminer-Addon 1.5.0 ist nicht mit REDAXO 5.5.1 kompatibel, wird dort aber im Installer aufgeführt.

**Comment by gharlan** [comment]
was passiert in R5.5.1?

**Comment by gharlan** [comment]
Es liegt an `rex::getDebugFlags()`:
https://github.com/FriendsOfREDAXO/adminer/blob/master/pages/index.php#L34

Das gibt es erst seit 5.6.

**Comment by AWqxKAWERbXo** [comment]
Genau. Hab das Issue aus den Augen verloren

**Comment by gharlan** [comment]
Ich hab nun die Kompatibilität zu R<5.6 wieder hergestellt.
