### ISSUE TITLE
Spaltenreihenfolge rex_article_slice

### ISSUE THREAD

**Issue by erraiva** [FriendsOfREDAXO/adminer#29]
Adminer, eines der geilsten Addons! :-)
Meine Anregung: in der Tabelle rex_article_slice die Spalten **article_id** und **module_id** nach vorne holen vor die Value-Spalten. Die beiden sind wichtiger als die leeren Value-Felder, finde ich. Danke und LG Heinz

**Comment by staabm** [comment]
gibt es in admin einer feature um das zu tun?

oder bedeutet dein vorschlag dass wir die mysql tabellen verändern sollen?

**Comment by tbaddade** [comment]
Eventuell ist das hier gemeint
https://github.com/redaxo/redaxo/issues/888

**Comment by staabm** [comment]
in dem verlinkten issue würde ich die gleichen fragen nochmal stellen wie im kommentar oben... :-)

**Comment by tbaddade** [comment]
> in dem verlinkten issue würde ich die gleichen fragen nochmal stellen wie im kommentar oben.

Ich dachte es wäre eindeutig, da sich das Issue im Core befindet und mit Structure gelabelt wurde :)

**Comment by staabm** [comment]
ich schließe hier und wir diskutieren weiter im duplikat redaxo/redaxo#888

danke für den input @erraiva
