### ISSUE TITLE
designs

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/adminer#3]
Hallo, danke für das AddOn. Wo muss ich denn die adminer.css ( design > https://www.adminer.org/#extras ) hochladen damit diese verwendet wird statt der default.css ? Oder könnte man die Auswahl der Designs per Dorpdown "irgendwie" integrieren?

**Comment by gharlan** [comment]
Da adminer über die Haupt-`index.php` des Backends ausgegeben wird, und man die `adminer.css` in den gleichen Ordner legen soll, könnte es eventuell klappen, wenn du sie einfach in den `redaxo`-Ordner legst, also quasi neben die `index.php`.
So richtig schön ist es nicht, aber könnte klappen.

Ansonsten werde ich hier wohl nichts integrieren für Auswahl des Design. Das Addon liegt aber ja auch bewusst hier bei den Friends, sodass es andere erweitern können.
Meine Arbeit an dem Addon wird sich wohl darauf beschränken, dass ich adminer ab und zu aktualisiere, und zusehe, dass es weiterhin funktioniert.

**Comment by mbodon** [comment]
Danke für deine schnelle Antwort.  Ich habe die Datei adminer.css in den redaxo-Ordner gelegt und es passt ... quick and dirty ;-)
