### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/adminer#32]
Min php und redaxo version ind die package.yml

**Comment by elricco** [comment]
👍 Japp - fänd ich auch gut - da ich gerade eine 5.3.0 update und gerne wissen würde ob / wann ich die Version von Adminer anhebe.

**Comment by gharlan** [comment]
Explizit eintragen finde ich gut und richtig!

Es wird aber wahrscheinlich min PHP 5.5 und min Rex 5.0 sein, sollte also in allen Versionen funktionieren.

**Comment by elricco** [comment]
Danke schonmal für die Info :)

**Comment by elricco** [comment]
Gerade von 1.4.0 auf 1.5.0 innerhalb eines REDAXO 5.5.1 geupdatet - wirft dann ein Whoops beim Aufruf von Adminer `Call to undefined method rex::getDebugFlags()` - index.php - Z.41

**Comment by gharlan** [comment]
Da hast du dir genau die falsche Version ausgesucht. Schau mal ins Changelog von 1.6, da steht:

> Kompatibilität zu REDAXO < 5.6 wieder hergestellt

;)
