### ISSUE TITLE
Update adminer

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/adminer#33]
Wg security vuln.: https://github.com/vrana/adminer/releases/v4.7.7

**Comment by gharlan** [comment]
Verstehst du, was er mit 

> Fix open redirect if Adminer is accessible at //adminer.php%2F@

meint?

Ich vermute, dass wir hier nicht betroffen sind, da adminer sowieso hinter dem redaxo-login sitzt. 
Aber bin mir nicht sicher, und ein Update schadet natürlich so oder so nicht.

**Comment by staabm** [comment]
Ich denke damit ist gemeint dass man von außen den user „beliebig umleiten lassen kann“. Ob das uns betrifft hab ich nicht weiter validiert
