### ISSUE TITLE
ErrorException (E_NOTICE) Array to string conversion

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/adminer#34]
Beim Klonen von Datensätzen in einer Tabelle:

**ErrorException:** Array to string conversion
**File:** redaxo/src/core/lib/util/type.php
**Line:** 60

<details>
<summary>Stacktrace</summary>

| Function                       | File                                                    | Line     |
| ------------------------------ | ------------------------------------------------------- | -------- |
| rex_error_handler::handleError | redaxo/src/core/lib/util/type.php                       | 60       |
| rex_type::cast                 | redaxo/src/core/lib/request.php                         | 201      |
| rex_request::arrayKeyCast      | redaxo/src/core/lib/request.php                         | 49       |
| rex_request::request           | redaxo/src/core/functions/function_rex_globals.php      | 36       |
| rex_request                    | redaxo/src/addons/theme/lib/developer/theme_manager.php | 41       |
| theme_manager::register        | redaxo/src/addons/theme/lib/developer/theme_manager.php | 27       |
| theme_manager::start           | redaxo/src/core/lib/extension.php                       | 49       |
| rex_extension::{closure}       | redaxo/src/core/lib/util/timer.php                      | 54       |
| rex_timer::measure             | redaxo/src/core/lib/extension.php                       | 56       |
| rex_extension::registerPoint   | redaxo/src/addons/developer/lib/manager.php             | 152      |
| rex_developer_manager::start   | redaxo/src/addons/developer/boot.php                    | 17       |
| rex_package->{closure}         | redaxo/src/core/lib/extension.php                       | 49       |
| rex_extension::{closure}       | redaxo/src/core/lib/util/timer.php                      | 54       |
| rex_timer::measure             | redaxo/src/core/lib/extension.php                       | 56       |
| rex_extension::registerPoint   | redaxo/src/core/packages.php                            | 31       |
| include_once                   | redaxo/src/core/backend.php                             | 200      |
| require                        | redaxo/src/core/boot.php                                | 137      |
| require                        | redaxo/index.php                                        | 9        |

</details>
<details>
<summary>System report (REDAXO 5.11.1, PHP 7.4.11, MariaDB 10.2.34)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.11.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.11     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.2.34 |
| Character set | utf8mb4         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |                     |
| ------------: | :------------------ |
|       Browser | Chrome/87.0.4280.88 |
|      Protocol | HTTP/2.0            |
|         HTTPS | yes                 |

| Packages                |             |
| ----------------------: | :---------- |
|            accessdenied | 1.0.6       |
|                  across | 3.0.0-dev23 |
|          across/backend | 3.0.0       |
|                 adminer | 1.8.1       |
|                  backup | 2.6.2       |
|                be_style | 2.11.1      |
|     be_style/customizer | 2.11.0      |
|         be_style/redaxo | 2.11.1      |
|                 bloecks | 3.0.0       |
|        bloecks/cutncopy | 3.0.0       |
|          bloecks/status | 3.0.0       |
|                    cke5 | 4.2.0       |
|                 cronjob | 2.7.1       |
|  cronjob/article_status | 2.7.1       |
| cronjob/optimize_tables | 2.7.1       |
|               developer | 3.9.0       |
|                  events | 2.0.0-dev   |
|                   feeds | 3.1         |
|                 install | 2.8.0       |
|                    iwcc | 1.1.2       |
|             maintenance | 2.4.1       |
|                markitup | 3.6.0       |
|                  mblock | 3.1.0       |
|           media_manager | 2.10.1      |
|               mediapool | 2.9.0       |
|                metainfo | 2.7.2       |
|                   mform | 5.3.1       |
|              mform/docs | 1.0         |
|                  minify | 2.2         |
|               phpmailer | 2.9.1       |
|                 project | dev         |
|        quick_navigation | 3.9.4       |
|                   sprog | 1.2.0       |
|               structure | 2.11.1      |
|       structure/content | 2.11.1      |
|       structure/history | 2.11.0      |
|       structure/version | 2.11.0      |
|                   theme | 1.2.0       |
|                uploader | 2.2.0       |
|                     url | 2.0.0-beta3 |
|                   users | 2.7.1       |
|                  watson | 2.2.0       |
|                    ycom | 4.0.3       |
|               ycom/auth | 4.0.3       |
|               ycom/docs | 4.0.3       |
|              ycom/group | 4.0.3       |
|                   yform | 3.4.1       |
|             yform/email | 3.4.1       |
|           yform/manager | 3.4.1       |
|             yform/tools | 3.4.1       |
|           yform_geo_osm | 1.2.3       |
|   yform_spam_protection | 1.0.5       |
|         yform_usability | 1.4         |
|                yrewrite | 2.7         |
|             zip_install | 1.1         |

</details>

**Comment by gharlan** [comment]
Da sind wir bei diesem Problem: https://github.com/redaxo/redaxo/issues/2900
Leider weiß ich immer noch nicht, wie  man es allgemein am besten lösen kann.
und hatte gehofft, dass es keine weiteren konstellationen geben wird.
die problematik damals hatte ich dann im developer-addon gelöst. Analog könnte man es bei deiner konstellation im theme-addon lösen, auch wenn das addon eigentlich nichts falsch macht.
Allgemeine Lösung wäre mir immer noch lieber, gerade weil sonst eben Addons was anpassen müssen, die eigentlich nichts falsch gemacht haben.

**Comment by gharlan** [comment]
Ich schließe hier mal, und habe das Core-Issue wieder geöffnet.
Hier im adminer lässt es sich nicht lösen (was du nicht wissen konntest).

**Comment by AWqxKAWERbXo** [comment]
Ich hab's vermutet, da es ja aus `redaxo/src/core/lib/util/type.php` kommt, aber man hier nachstellen kann. Danke!
