### ISSUE TITLE
Hinweis: Adminer-Addon nicht PHP8-kompatibel - Safe Mode-Button fehlt

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/adminer#35]
Ich mach das Issue mal rein, weil es mir nur mit Adminer aufgefallen ist:

![image](https://user-images.githubusercontent.com/3855487/104305526-11e23b80-54cd-11eb-8e6e-d0e7d0607262.png)
**Error:** Call to undefined function get_magic_quotes_gpc()
**File:** redaxo\src\addons\adminer\vendor\adminer.php
**Line:** 20

<details>
<summary>Stacktrace</summary>

| Function                              | File                                         | Line     |
| ------------------------------------- | -------------------------------------------- | -------- |
| remove_slashes                        | redaxo\src\addons\adminer\vendor\adminer.php | 169      |
| include                               | redaxo\src\addons\adminer\pages\index.php    | 50       |
| include                               | redaxo\src\core\lib\packages\package.php     | 272      |
| rex_package->includeFile              | redaxo\src\core\lib\be\controller.php        | 470      |
| rex_be_controller::{closure}          | redaxo\src\core\lib\util\timer.php           | 63       |
| rex_timer::measure                    | redaxo\src\core\lib\be\controller.php        | 471      |
| rex_be_controller::includePath        | redaxo\src\core\lib\be\controller.php        | 409      |
| rex_be_controller::includeCurrentPage | redaxo\src\core\backend.php                  | 236      |
| require                               | redaxo\src\core\boot.php                     | 137      |
| require                               | redaxo\index.php                             | 9        |

</details>
<details>
<summary>System report (REDAXO 5.12.0-dev, PHP 8.0.0, MariaDB 10.4.17)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.0-dev |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 8.0.0                          |
|       OPcache | no                             |
|        Xdebug | no                             |
|       Warning | Das Setup wird ohne HTTPS/Verschlüsselung durchgeführt. Es wird empfohlen jegliche Frontend und Backend aufrufe nur mittels HTTPS durchzuführen, um die Privatsphäre und den Datenschutz zu gewährleisten. |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.4.17 |
| Character set | utf8mb4         |

| Server        |                |
| ------------: | :------------- |
|            OS | WINNT          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.46  |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/87.0.4280.141 |
|      Protocol | HTTP/1.1             |
|         HTTPS | no                   |

| Packages                |             |
| ----------------------: | :---------- |
|            2factor_auth | 1.0.0       |
|            accessdenied | 1.0.6       |
|                  across | 3.0.0-dev24 |
|                 adminer | 1.8.1       |
|                  backup | 2.6.2       |
|                be_style | 2.11.1      |
|     be_style/customizer | 2.11.0      |
|         be_style/redaxo | 2.11.1      |
|         be_style_fluent | 3.0.0       |
|                 bloecks | 3.0.0       |
|        bloecks/cutncopy | 3.0.0       |
|          bloecks/status | 3.0.0       |
|                    cke5 | 4.0.4       |
|                 cronjob | 2.7.1       |
|  cronjob/article_status | 2.7.1       |
| cronjob/optimize_tables | 2.7.1       |
|                   debug | 1.1.0-dev   |
|               developer | 3.9.0       |
|                  events | 2.0.0-dev   |
|                   feeds | 3.1         |
|                 install | 2.9.0-dev   |
|                    iwcc | 2.0.0-beta6 |
|             maintenance | 2.4.1       |
|                  mblock | 3.1.0       |
|           media_manager | 2.10.1      |
|               mediapool | 2.9.0       |
|                metainfo | 2.7.2       |
|                   mform | 5.3.1       |
|              mform/docs | 1.0         |
|               phpmailer | 2.9.1       |
|                 project | dev         |
|               search_it | 6.7.2       |
|  search_it/autocomplete | 6.7.2       |
| search_it/documentation | 6.7.2       |
|     search_it/plaintext | 6.7.2       |
|         search_it/stats | 6.7.2       |
|                   sprog | 1.2.0       |
|               structure | 2.12.0-dev  |
|       structure/content | 2.11.1      |
|                   theme | 1.1.1       |
|                uploader | 2.1.0       |
|                     url | 2.0.0-beta3 |
|                   users | 2.8.0-dev   |
|                  watson | 2.2.0       |
|                    ycom | 4.0.3       |
|               ycom/auth | 4.0.3       |
|               ycom/docs | 4.0.3       |
|              ycom/group | 4.0.3       |
|                   yform | 3.4.1       |
|              yform/docs | 3.3.1       |
|             yform/email | 3.4.1       |
|           yform/manager | 3.4.1       |
|              yform/rest | 3.4.1       |
|             yform/tools | 3.4.1       |
|           yform_geo_osm | 1.2.3       |
|   yform_spam_protection | 1.0.5       |
|         yform_usability | 1.4         |
|                yrewrite | 2.6         |
|             zip_install | 1.1         |

</details>

**Comment by gharlan** [comment]
Du verwendest adminer 1.8.1, und in 1.8.2 ist es gefixt.

**Comment by AWqxKAWERbXo** [comment]
thx - kannst du dir erklären, warum der Safe Mode Button fehlt?

**Comment by gharlan** [comment]
Das ist die Bedingung für den Button: https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/lib/error_handler.php#L209-L211
~Ggf. war der Safemode schon aktiv?~ Nee, das kann eigentlich ja nicht sein.

**Comment by AWqxKAWERbXo** [comment]
Ah, der Safe Mode war aktiv - da ich adminer in die Liste der System Addons aufgenommen habe.
