### ISSUE TITLE
Unsupported operand types: string * string

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/adminer#36]
Bei der Suche innerhalb der Datenbanktabellen und anschließendem Anklicken eines Treffers.

Copy Markdown funktioniert jedoch nicht mehr innerhalb des Whoops. Aktuelle dev-Version von R5.12

![image](https://user-images.githubusercontent.com/3855487/104306183-eca1fd00-54cd-11eb-833c-6781e95c4654.png)

**Comment by gharlan** [comment]
Auch mit 1.8.2?

**Comment by AWqxKAWERbXo** [comment]
Ich habe festgestellt, dass der Installer nicht funktioniert, wenn man ihn als System-Addon deklariert und dann via Safe Mode updatet. Siehe redaxo/redaxo

https://github.com/redaxo/redaxo/pull/4316

Deswegen nahm ich fälschlicherweise an, er wäre geupdatet - es kam auch eine Erfolgsmeldung.

**Comment by AWqxKAWERbXo** [comment]
(ja, so ist das, wenn man mitten im Entwickeln ist. Irgendwas anders läuft schief. Der Installer updatet auch so nicht. Liegt sicherlich an was spezifischem von XAMPP.)

**Comment by AWqxKAWERbXo** [comment]
Auch in der aktuellen Installer-Fassung 1.8.2 tritt das Problem auf.

**Comment by gharlan** [comment]
Das ist ein "Bug" (oder sagen wir: neues Problem seit PHP 8) in adminer selbst, und lässt sich hier im Addon nicht lösen.

**Comment by gharlan** [comment]
https://sourceforge.net/p/adminer/bugs-and-features/
Hat jemand einen sourceforge Account? ;)

**Comment by aeberhard** [comment]
@gharlan ich hab meinen uralten User wieder ausgegraben. Schreib mir einfach einen Text und dann kann ich da ein Ticket anlegen.

**Comment by gharlan** [comment]
@aeberhard Super, danke! Hier mein Textvorschlag:

Title:
> [PHP 8] Error: Unsupported operand types: string * string

Text:
> When I go to the data page of a table, I get this error with PHP 8:
> > TypeError: Unsupported operand types: string * string
>
> The error seems to come from `Min_SQL::select()`.

**Comment by aeberhard** [comment]
Kann das gerne einstellen.
Aber ist adminer nicht auch auf github!? https://github.com/vrana/adminer

**Comment by gharlan** [comment]
Ja, aber ohne Issue-Tracker, der liegt noch bei sourceforge.

**Comment by aeberhard** [comment]
Ok ich mach mal 

https://sourceforge.net/p/adminer/bugs-and-features/778/

**Comment by bitshiftersgmbh** [comment]
Hab das Problem auch gerade. Werd jetzt erstmal zurück zu PHP 7 gehen, da ich das Tool brauche.

![Screenshot 2021-02-02 111815](https://user-images.githubusercontent.com/7023022/106586402-b396fe80-6548-11eb-999d-9fefb25dd6e7.png)
