### ISSUE TITLE
Addon im Installer stellen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/adminer#4]
Es gab im Slack den Wunsch das Addon im Installer zu haben.
@gharlan könntest Du das machen? Wenn nicht hättest Du was dagegen wenn ich das dann mache?

LG
Oliver

**Comment by tbaddade** [comment]
@olien Der Adminer erscheint im Installer. Klick mal ggf. das Refreshicon.

**Comment by olien** [comment]
Ok. Stimmt. Hatte es nicht geprüft. 
Danke für die Antwort.
