### ISSUE TITLE
Disable in Live-Mode / REDAXO >= 5.16 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/adminer#45]
**Feature description / Feature Beschreibung**

**Comment by AWqxKAWERbXo** [comment]
Fände ich nicht gut, wenn ich das jetzt richtig verstehe. Auch auf Live-Seiten möchte ich - authentifiziert über REDAXO - direkt über Adminer auf der Datenbank arbeiten können.

**Comment by skerbis** [comment]
der Live-Mode ist ein besonderer Modus um das Backend zu "festigen". Deshalb können dort auch keine Module oder Templates bearbeitet werden oder Installationen durchgeführt werden. Der Live-Mode muss händisch in der Config.yml aktiviert werden @alxndr-w
